- name: Provision Vagrant
  hosts: all
  user: vagrant
  become: yes
  gather_facts: true

  roles:
    - { role: ntp }
    #- { role: docker }
    - { role: python27 }
    #- { role: postgresql-server }
    - { role: grafana }
    #- { role: springboot }
    - { role: nginx }
    - { role: elk }
